import { ClerkProvider } from "@clerk/nextjs";
import type { Metadata } from "next";
import "./globals.css";
import { dark } from "@clerk/themes";
import { Mulish } from "next/font/google";
const mulish = Mulish({
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${mulish.className} dark antialiased`}>
				<ClerkProvider appearance={{ baseTheme: dark }}>{children}</ClerkProvider>
			</body>
		</html>
	);
}
